version: "3.9"
services:
  backend:
    build: .
    container_name: 'api_backend'
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - ./app:/app/app
      - ./db:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ai_agent
      POSTGRES_USER: deepyes02
      POSTGRES_PASSWORD: yEti-2025-yAk-ai
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
    build: ./frontend
    container_name : web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run dev
volumes:
  pg_data: